apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/cloud-hypervisor-provider

patches:
  - path: patch-manager-args.yaml
    target:
      group: apps
      version: v1
      kind: DaemonSet
      namespace: cloud-hypervisor-provider-system
      name: cloud-hypervisor-provider-controller-manager

