apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - github.com/ironcore-dev/dpservice/config/default?ref=v0.3.19

images:
  - name: dpservice
    newName: ghcr.io/ironcore-dev/dpservice
    newTag: v0.3.19

patches:
  - path: dpservice-tap.yaml
    target:
      kind: DaemonSet
      name: dpservice
      namespace: system
