apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: metalbond
  labels:
    app: metalbond
spec:
  selector:
    matchLabels:
      app: metalbond
  template:
    metadata:
      labels:
        app: metalbond
    spec:
      hostNetwork: true
      containers:
      - name: metalbond
        image: ghcr.io/ironcore-dev/metalbond:master
        command:
          - "metalbond"
          - "server"
          - "--listen"
          - "[::1]:4711"
          - "--http"
          - "[::1]:4712"
          - "--keepalive"
          - "3"
