apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ceph-volume-provider-system

resources:
  - poollet-rbac
  - github.com/ironcore-dev/ceph-provider/config/ceph-volume-provider/default?ref=v0.5.0

images:
  - name: volumepoollet
    newName: ghcr.io/ironcore-dev/ironcore-volumepoollet
    newTag: v0.5.0
  - name: ceph-volume-provider
    newName: ghcr.io/ironcore-dev/ceph-volume-provider
    newTag: v0.5.0

patches:
  - path: patch-manager-deployment.yaml
  - patch: |-
      apiVersion: v1
      kind: Namespace
      metadata:
        name: ceph-volume-provider-system
      $patch: delete
