apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - github.com/ironcore-dev/ironcore/config/etcdless?ref=ddcdb7671438c53015e2455090e069e0ee96674a
  - certificates.yaml

images:
  - name: apiserver
    newName: ghcr.io/ironcore-dev/ironcore-apiserver
    newTag: sha-ddcdb76
  - name: controller
    newName: ghcr.io/ironcore-dev/ironcore-controller-manager
    newTag: sha-ddcdb76

patches:
  - path: patch-apiserver-deployment.yaml
  - path: patch-apiserver-service.yaml
