apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: libvirt-provider

resources:
  - ../../../base/libvirt-provider
  - ../../../base/machine-classes
  - supported-machine-classes-configmap.yaml

patches:
  - path: patch-manager-args.yaml
    target:
      group: apps
      version: v1
      kind: DaemonSet
      namespace: libvirt-provider-system
      name: libvirt-provider-controller-manager
