apiVersion: compute.ironcore.dev/v1alpha1
kind: Machine
metadata:
  name: webapp
spec:
  image: ghcr.io/ironcore-dev/os-images/gardenlinux:latest
    #  image: ghcr.io/ironcore-dev/os-images/gardenlinux-amd64:latest
  networkInterfaces:
    - name: default
      networkInterfaceRef:
        name: webapp
  machineClassRef:
    name: t3-small
  ignitionRef:
    name: ignition
---
apiVersion: networking.ironcore.dev/v1alpha1
kind: Network
metadata:
  name: webapp
---
apiVersion: networking.ironcore.dev/v1alpha1
kind: VirtualIP
metadata:
  name: webapp
spec:
  ipFamily: IPv4
  type: Public
---
apiVersion: networking.ironcore.dev/v1alpha1
kind: NetworkInterface
metadata:
  labels:
    foo: bar
  name: webapp
spec:
  networkRef:
    name: webapp
  ipFamilies:
    - IPv4
  ips:
    - value: 10.0.0.1 # internal IP
  virtualIP:
    virtualIPRef:
      name: webapp
---
apiVersion: v1
data:
  ignition.yaml: eyJpZ25pdGlvbiI6eyJ2ZXJzaW9uIjoiMy4zLjAifSwicGFzc3dkIjp7InVzZXJzIjpbeyJncm91cHMiOlsid2hlZWwiXSwiaG9tZURpciI6Ii9ob21lL2lyb25jb3JlIiwibmFtZSI6Imlyb25jb3JlIiwicGFzc3dvcmRIYXNoIjoiJDYkR0VndzRBT09NNTdXSU9sUSRHZ1p5MVg3N3Rwbi8xZTE1NmRlRldIMVVQd29wbWQ2dTZHaWlHNTFob21lbjJ6aGNWQ0Fhai9OUXYvbDF4MVJwSVIxUHZ5TWhYQzdzMG5iZTNLbXE0MCIsInNoZWxsIjoiL2Jpbi9iYXNoIn1dfSwic3RvcmFnZSI6eyJkaXJlY3RvcmllcyI6W3siZ3JvdXAiOnsibmFtZSI6Imlyb25jb3JlIn0sInBhdGgiOiIvaG9tZS9pcm9uY29yZS8uc3NoIiwidXNlciI6eyJuYW1lIjoiaXJvbmNvcmUifSwibW9kZSI6NDQ4fV0sImZpbGVzIjpbeyJwYXRoIjoiL2V0Yy9zeXN0ZW1kL3Jlc29sdmVkLmNvbmYuZC9kbnMuY29uZiIsImNvbnRlbnRzIjp7ImNvbXByZXNzaW9uIjoiIiwic291cmNlIjoiZGF0YTosJTVCUmVzb2x2ZSU1RCUwQUROUyUzRDguOC44LjglMEEifSwibW9kZSI6NDIwfV19LCJzeXN0ZW1kIjp7InVuaXRzIjpbeyJjb250ZW50cyI6IltVbml0XVxuRGVzY3JpcHRpb249RW5hYmxlIGVhc3kgcGFzc3dvcmQgbG9naW5cblxuW1NlcnZpY2VdXG5UaW1lb3V0U3RhcnRTZWM9MFxuRXhlY1N0YXJ0PS9iaW4vYmFzaCAtYyBcInNlZCAtaSAtZSAncy9eXFxzKkF1dGhlbnRpY2F0aW9uTWV0aG9kc1xcc1xcKy4qJC8jIFx1MDAyNi8nIC1lICcvXlxccypQYXNzd29yZEF1dGhlbnRpY2F0aW9uXFxzXFwrL2QnIC1lICckYVBhc3N3b3JkQXV0aGVudGljYXRpb24geWVzJyAvZXRjL3NzaC9zc2hkX2NvbmZpZ1wiXG5cbltJbnN0YWxsXVxuV2FudGVkQnk9bXVsdGktdXNlci50YXJnZXRcbiIsImVuYWJsZWQiOnRydWUsIm5hbWUiOiJwYXNzd2Quc2VydmljZSJ9LHsiZW5hYmxlZCI6dHJ1ZSwibmFtZSI6InNzaC5zZXJ2aWNlIn1dfX0K
kind: Secret
metadata:
  creationTimestamp: null
  name: ignition

