apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - github.com/ironcore-dev/metalnet/config/default?ref=v0.3.11

images:
  - name: controller
    newName: ghcr.io/ironcore-dev/metalnet-controller-manager
    newTag: v0.3.11

patches:
  - path: add-metalnet-args.yaml
    target:
      group: apps
      version: v1
      kind: DaemonSet
      namespace: metalnet-system
      name: metalnet-controller-manager
