apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://raw.githubusercontent.com/rook/rook/v1.18.9/deploy/examples/crds.yaml
  - https://raw.githubusercontent.com/rook/rook/v1.18.9/deploy/examples/common.yaml
  - https://raw.githubusercontent.com/rook/rook/v1.18.9/deploy/examples/monitoring/rbac.yaml
  - https://raw.githubusercontent.com/rook/rook/v1.18.9/deploy/examples/operator.yaml

patches:
  - path: configmap-patch.yaml
  - path: deployment-patch.yaml
